name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME }}
        DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new version of {{ EVENT_PAYLOAD.repository.full_name }} has been pushed to the remote repository by {{ EVENT_PAYLOAD.pusher.name }}. Link to the repository: {{ EVENT_PAYLOAD.repository.html_url }}'
